/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.CartesianControl
{
    public class CartesianPosture : Message
    {
        public const string RosMessageName = "cartesian_control_msgs/CartesianPosture";

        //  Posture joint names may reflect a subset of all available joints (empty posture definitions are
        //  also possible). The length of posture_joint_names and posture_joint_values have to be equal.
        public string[] posture_joint_names { get; set; }
        public double[] posture_joint_values { get; set; }

        public CartesianPosture()
        {
            this.posture_joint_names = new string[0];
            this.posture_joint_values = new double[0];
        }

        public CartesianPosture(string[] posture_joint_names, double[] posture_joint_values)
        {
            this.posture_joint_names = posture_joint_names;
            this.posture_joint_values = posture_joint_values;
        }
    }
}
