/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.CartesianControl
{
    public class FollowCartesianTrajectoryResult : Message
    {
        public const string RosMessageName = "cartesian_control_msgs/FollowCartesianTrajectoryResult";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public int error_code { get; set; }
        public const int SUCCESSFUL = 0;
        public const int INVALID_GOAL = -1; //  e.g. illegal quaternions in poses
        public const int INVALID_JOINTS = -2;
        public const int OLD_HEADER_TIMESTAMP = -3;
        public const int PATH_TOLERANCE_VIOLATED = -4;
        public const int GOAL_TOLERANCE_VIOLATED = -5;
        public const int INVALID_POSTURE = -6;
        public string error_string { get; set; }

        public FollowCartesianTrajectoryResult()
        {
            this.error_code = 0;
            this.error_string = "";
        }

        public FollowCartesianTrajectoryResult(int error_code, string error_string)
        {
            this.error_code = error_code;
            this.error_string = error_string;
        }
    }
}
