/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.CartesianControl
{
    public class FollowCartesianTrajectoryFeedback : Message
    {
        public const string RosMessageName = "cartesian_control_msgs/FollowCartesianTrajectoryFeedback";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public Header header { get; set; }
        public string tcp_frame { get; set; }
        public CartesianTrajectoryPoint desired { get; set; }
        public CartesianTrajectoryPoint actual { get; set; }
        public CartesianTrajectoryPoint error { get; set; }

        public FollowCartesianTrajectoryFeedback()
        {
            this.header = new Header();
            this.tcp_frame = "";
            this.desired = new CartesianTrajectoryPoint();
            this.actual = new CartesianTrajectoryPoint();
            this.error = new CartesianTrajectoryPoint();
        }

        public FollowCartesianTrajectoryFeedback(Header header, string tcp_frame, CartesianTrajectoryPoint desired, CartesianTrajectoryPoint actual, CartesianTrajectoryPoint error)
        {
            this.header = header;
            this.tcp_frame = tcp_frame;
            this.desired = desired;
            this.actual = actual;
            this.error = error;
        }
    }
}
