/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.CartesianControl
{
    public class FollowCartesianTrajectoryGoal : Message
    {
        public const string RosMessageName = "cartesian_control_msgs/FollowCartesianTrajectoryGoal";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public CartesianTrajectory trajectory { get; set; }
        public CartesianTolerance path_tolerance { get; set; }
        public CartesianTolerance goal_tolerance { get; set; }
        public Duration goal_time_tolerance { get; set; }

        public FollowCartesianTrajectoryGoal()
        {
            this.trajectory = new CartesianTrajectory();
            this.path_tolerance = new CartesianTolerance();
            this.goal_tolerance = new CartesianTolerance();
            this.goal_time_tolerance = new Duration();
        }

        public FollowCartesianTrajectoryGoal(CartesianTrajectory trajectory, CartesianTolerance path_tolerance, CartesianTolerance goal_tolerance, Duration goal_time_tolerance)
        {
            this.trajectory = trajectory;
            this.path_tolerance = path_tolerance;
            this.goal_tolerance = goal_tolerance;
            this.goal_time_tolerance = goal_time_tolerance;
        }
    }
}
