/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class GripperCommandAction : Message
    {
        public const string RosMessageName = "control_msgs/GripperCommandAction";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public GripperCommandActionGoal action_goal { get; set; }
        public GripperCommandActionResult action_result { get; set; }
        public GripperCommandActionFeedback action_feedback { get; set; }

        public GripperCommandAction()
        {
            this.action_goal = new GripperCommandActionGoal();
            this.action_result = new GripperCommandActionResult();
            this.action_feedback = new GripperCommandActionFeedback();
        }

        public GripperCommandAction(GripperCommandActionGoal action_goal, GripperCommandActionResult action_result, GripperCommandActionFeedback action_feedback)
        {
            this.action_goal = action_goal;
            this.action_result = action_result;
            this.action_feedback = action_feedback;
        }
    }
}
