/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class GripperCommandResult : Message
    {
        public const string RosMessageName = "control_msgs/GripperCommandResult";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public double position { get; set; }
        //  The current gripper gap size (in meters)
        public double effort { get; set; }
        //  The current effort exerted (in Newtons)
        public bool stalled { get; set; }
        //  True iff the gripper is exerting max effort and not moving
        public bool reached_goal { get; set; }
        //  True iff the gripper position has reached the commanded setpoint

        public GripperCommandResult()
        {
            this.position = 0.0;
            this.effort = 0.0;
            this.stalled = false;
            this.reached_goal = false;
        }

        public GripperCommandResult(double position, double effort, bool stalled, bool reached_goal)
        {
            this.position = position;
            this.effort = effort;
            this.stalled = stalled;
            this.reached_goal = reached_goal;
        }
    }
}
