/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class JointTrajectoryAction : Message
    {
        public const string RosMessageName = "control_msgs/JointTrajectoryAction";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public JointTrajectoryActionGoal action_goal { get; set; }
        public JointTrajectoryActionResult action_result { get; set; }
        public JointTrajectoryActionFeedback action_feedback { get; set; }

        public JointTrajectoryAction()
        {
            this.action_goal = new JointTrajectoryActionGoal();
            this.action_result = new JointTrajectoryActionResult();
            this.action_feedback = new JointTrajectoryActionFeedback();
        }

        public JointTrajectoryAction(JointTrajectoryActionGoal action_goal, JointTrajectoryActionResult action_result, JointTrajectoryActionFeedback action_feedback)
        {
            this.action_goal = action_goal;
            this.action_result = action_result;
            this.action_feedback = action_feedback;
        }
    }
}
