/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class PointHeadAction : Message
    {
        public const string RosMessageName = "control_msgs/PointHeadAction";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public PointHeadActionGoal action_goal { get; set; }
        public PointHeadActionResult action_result { get; set; }
        public PointHeadActionFeedback action_feedback { get; set; }

        public PointHeadAction()
        {
            this.action_goal = new PointHeadActionGoal();
            this.action_result = new PointHeadActionResult();
            this.action_feedback = new PointHeadActionFeedback();
        }

        public PointHeadAction(PointHeadActionGoal action_goal, PointHeadActionResult action_result, PointHeadActionFeedback action_feedback)
        {
            this.action_goal = action_goal;
            this.action_result = action_result;
            this.action_feedback = action_feedback;
        }
    }
}
