/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class PointHeadFeedback : Message
    {
        public const string RosMessageName = "control_msgs/PointHeadFeedback";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public double pointing_angle_error { get; set; }

        public PointHeadFeedback()
        {
            this.pointing_angle_error = 0.0;
        }

        public PointHeadFeedback(double pointing_angle_error)
        {
            this.pointing_angle_error = pointing_angle_error;
        }
    }
}
