/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class SingleJointPositionGoal : Message
    {
        public const string RosMessageName = "control_msgs/SingleJointPositionGoal";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public double position { get; set; }
        public Duration min_duration { get; set; }
        public double max_velocity { get; set; }

        public SingleJointPositionGoal()
        {
            this.position = 0.0;
            this.min_duration = new Duration();
            this.max_velocity = 0.0;
        }

        public SingleJointPositionGoal(double position, Duration min_duration, double max_velocity)
        {
            this.position = position;
            this.min_duration = min_duration;
            this.max_velocity = max_velocity;
        }
    }
}
