/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class SingleJointPositionFeedback : Message
    {
        public const string RosMessageName = "control_msgs/SingleJointPositionFeedback";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public Header header { get; set; }
        public double position { get; set; }
        public double velocity { get; set; }
        public double error { get; set; }

        public SingleJointPositionFeedback()
        {
            this.header = new Header();
            this.position = 0.0;
            this.velocity = 0.0;
            this.error = 0.0;
        }

        public SingleJointPositionFeedback(Header header, double position, double velocity, double error)
        {
            this.header = header;
            this.position = position;
            this.velocity = velocity;
            this.error = error;
        }
    }
}
