/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.CartesianControl
{
    public class CartesianTrajectory : Message
    {
        public const string RosMessageName = "cartesian_control_msgs/CartesianTrajectory";

        //  header.frame_id is the frame in which all data from CartesianTrajectoryPoint[] is given
        public Header header { get; set; }
        public CartesianTrajectoryPoint[] points { get; set; }
        public string controlled_frame { get; set; }

        public CartesianTrajectory()
        {
            this.header = new Header();
            this.points = new CartesianTrajectoryPoint[0];
            this.controlled_frame = "";
        }

        public CartesianTrajectory(Header header, CartesianTrajectoryPoint[] points, string controlled_frame)
        {
            this.header = header;
            this.points = points;
            this.controlled_frame = controlled_frame;
        }
    }
}
