/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Actionlib;

namespace RosSharp.RosBridgeClient.MessageTypes.CartesianControl
{
    public class FollowCartesianTrajectoryActionResult : Message
    {
        public const string RosMessageName = "cartesian_control_msgs/FollowCartesianTrajectoryActionResult";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public Header header { get; set; }
        public GoalStatus status { get; set; }
        public FollowCartesianTrajectoryResult result { get; set; }

        public FollowCartesianTrajectoryActionResult()
        {
            this.header = new Header();
            this.status = new GoalStatus();
            this.result = new FollowCartesianTrajectoryResult();
        }

        public FollowCartesianTrajectoryActionResult(Header header, GoalStatus status, FollowCartesianTrajectoryResult result)
        {
            this.header = header;
            this.status = status;
            this.result = result;
        }
    }
}
