/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.CartesianControl
{
    public class FollowCartesianTrajectoryAction : Message
    {
        public const string RosMessageName = "cartesian_control_msgs/FollowCartesianTrajectoryAction";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public FollowCartesianTrajectoryActionGoal action_goal { get; set; }
        public FollowCartesianTrajectoryActionResult action_result { get; set; }
        public FollowCartesianTrajectoryActionFeedback action_feedback { get; set; }

        public FollowCartesianTrajectoryAction()
        {
            this.action_goal = new FollowCartesianTrajectoryActionGoal();
            this.action_result = new FollowCartesianTrajectoryActionResult();
            this.action_feedback = new FollowCartesianTrajectoryActionFeedback();
        }

        public FollowCartesianTrajectoryAction(FollowCartesianTrajectoryActionGoal action_goal, FollowCartesianTrajectoryActionResult action_result, FollowCartesianTrajectoryActionFeedback action_feedback)
        {
            this.action_goal = action_goal;
            this.action_result = action_result;
            this.action_feedback = action_feedback;
        }
    }
}
