/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class FollowJointTrajectoryResult : Message
    {
        public const string RosMessageName = "control_msgs/FollowJointTrajectoryResult";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public int error_code { get; set; }
        public const int SUCCESSFUL = 0;
        public const int INVALID_GOAL = -1;
        public const int INVALID_JOINTS = -2;
        public const int OLD_HEADER_TIMESTAMP = -3;
        public const int PATH_TOLERANCE_VIOLATED = -4;
        public const int GOAL_TOLERANCE_VIOLATED = -5;
        //  Human readable description of the error code. Contains complementary
        //  information that is especially useful when execution fails, for instance:
        //  - INVALID_GOAL: The reason for the invalid goal (e.g., the requested
        //    trajectory is in the past).
        //  - INVALID_JOINTS: The mismatch between the expected controller joints
        //    and those provided in the goal.
        //  - PATH_TOLERANCE_VIOLATED and GOAL_TOLERANCE_VIOLATED: Which joint
        //    violated which tolerance, and by how much.
        public string error_string { get; set; }

        public FollowJointTrajectoryResult()
        {
            this.error_code = 0;
            this.error_string = "";
        }

        public FollowJointTrajectoryResult(int error_code, string error_string)
        {
            this.error_code = error_code;
            this.error_string = error_string;
        }
    }
}
