/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;
using RosSharp.RosBridgeClient.MessageTypes.Trajectory;

namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class FollowJointTrajectoryFeedback : Message
    {
        public const string RosMessageName = "control_msgs/FollowJointTrajectoryFeedback";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public Header header { get; set; }
        public string[] joint_names { get; set; }
        public JointTrajectoryPoint desired { get; set; }
        public JointTrajectoryPoint actual { get; set; }
        public JointTrajectoryPoint error { get; set; }

        public FollowJointTrajectoryFeedback()
        {
            this.header = new Header();
            this.joint_names = new string[0];
            this.desired = new JointTrajectoryPoint();
            this.actual = new JointTrajectoryPoint();
            this.error = new JointTrajectoryPoint();
        }

        public FollowJointTrajectoryFeedback(Header header, string[] joint_names, JointTrajectoryPoint desired, JointTrajectoryPoint actual, JointTrajectoryPoint error)
        {
            this.header = header;
            this.joint_names = joint_names;
            this.desired = desired;
            this.actual = actual;
            this.error = error;
        }
    }
}
