/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class FollowJointTrajectoryAction : Message
    {
        public const string RosMessageName = "control_msgs/FollowJointTrajectoryAction";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public FollowJointTrajectoryActionGoal action_goal { get; set; }
        public FollowJointTrajectoryActionResult action_result { get; set; }
        public FollowJointTrajectoryActionFeedback action_feedback { get; set; }

        public FollowJointTrajectoryAction()
        {
            this.action_goal = new FollowJointTrajectoryActionGoal();
            this.action_result = new FollowJointTrajectoryActionResult();
            this.action_feedback = new FollowJointTrajectoryActionFeedback();
        }

        public FollowJointTrajectoryAction(FollowJointTrajectoryActionGoal action_goal, FollowJointTrajectoryActionResult action_result, FollowJointTrajectoryActionFeedback action_feedback)
        {
            this.action_goal = action_goal;
            this.action_result = action_result;
            this.action_feedback = action_feedback;
        }
    }
}
