/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class GripperCommandGoal : Message
    {
        public const string RosMessageName = "control_msgs/GripperCommandGoal";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public GripperCommand command { get; set; }

        public GripperCommandGoal()
        {
            this.command = new GripperCommand();
        }

        public GripperCommandGoal(GripperCommand command)
        {
            this.command = command;
        }
    }
}
