/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Trajectory;

namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class JointTrajectoryGoal : Message
    {
        public const string RosMessageName = "control_msgs/JointTrajectoryGoal";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public JointTrajectory trajectory { get; set; }

        public JointTrajectoryGoal()
        {
            this.trajectory = new JointTrajectory();
        }

        public JointTrajectoryGoal(JointTrajectory trajectory)
        {
            this.trajectory = trajectory;
        }
    }
}
