/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Std;

namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class PidState : Message
    {
        public const string RosMessageName = "control_msgs/PidState";

        public Header header { get; set; }
        public Duration timestep { get; set; }
        public double error { get; set; }
        public double error_dot { get; set; }
        public double p_error { get; set; }
        public double i_error { get; set; }
        public double d_error { get; set; }
        public double p_term { get; set; }
        public double i_term { get; set; }
        public double d_term { get; set; }
        public double i_max { get; set; }
        public double i_min { get; set; }
        public double output { get; set; }

        public PidState()
        {
            this.header = new Header();
            this.timestep = new Duration();
            this.error = 0.0;
            this.error_dot = 0.0;
            this.p_error = 0.0;
            this.i_error = 0.0;
            this.d_error = 0.0;
            this.p_term = 0.0;
            this.i_term = 0.0;
            this.d_term = 0.0;
            this.i_max = 0.0;
            this.i_min = 0.0;
            this.output = 0.0;
        }

        public PidState(Header header, Duration timestep, double error, double error_dot, double p_error, double i_error, double d_error, double p_term, double i_term, double d_term, double i_max, double i_min, double output)
        {
            this.header = header;
            this.timestep = timestep;
            this.error = error;
            this.error_dot = error_dot;
            this.p_error = p_error;
            this.i_error = i_error;
            this.d_error = d_error;
            this.p_term = p_term;
            this.i_term = i_term;
            this.d_term = d_term;
            this.i_max = i_max;
            this.i_min = i_min;
            this.output = output;
        }
    }
}
