/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Control
{
    public class SingleJointPositionAction : Message
    {
        public const string RosMessageName = "control_msgs/SingleJointPositionAction";

        //  ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
        public SingleJointPositionActionGoal action_goal { get; set; }
        public SingleJointPositionActionResult action_result { get; set; }
        public SingleJointPositionActionFeedback action_feedback { get; set; }

        public SingleJointPositionAction()
        {
            this.action_goal = new SingleJointPositionActionGoal();
            this.action_result = new SingleJointPositionActionResult();
            this.action_feedback = new SingleJointPositionActionFeedback();
        }

        public SingleJointPositionAction(SingleJointPositionActionGoal action_goal, SingleJointPositionActionResult action_result, SingleJointPositionActionFeedback action_feedback)
        {
            this.action_goal = action_goal;
            this.action_result = action_result;
            this.action_feedback = action_feedback;
        }
    }
}
